### ISSUE TITLE
ModuleNotFoundError: No module named 'elftools

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/python#118]
```
---> Running application from script (app.sh) ...
--
  | Traceback (most recent call last):
  | File "thoth-package-analyzer", line 25, in <module>
  | from thoth.package_analyzer import __version__ as analyzer_version
  | File "/opt/app-root/src/thoth/package_analyzer/__init__.py", line 25, in <module>
  | from .python import PythonDigestsFetcher
  | File "/opt/app-root/src/thoth/package_analyzer/python/__init__.py", line 20, in <module>
  | from .fetch import PythonDigestsFetcher
  | File "/opt/app-root/src/thoth/package_analyzer/python/fetch.py", line 22, in <module>
  | from thoth.python import Source
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/__init__.py", line 20, in <module>
  | from .digests_fetcher import DigestsFetcherBase
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/digests_fetcher.py", line 23, in <module>
  | from .source import Source
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/source.py", line 35, in <module>
  | from .artifact import Artifact
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/artifact.py", line 28, in <module>
  | from elftools.elf.elffile import ELFFile
  | ModuleNotFoundError: No module named 'elftools'
```

**Comment by bissenbay** [comment]
@fridex Should I import `efltools` and PR?
