### ISSUE TITLE
jupyterlab-requirements is failing due to new thoth-python release

### ISSUE THREAD

**Issue by pacospace** [thoth-station/python#362]
**Describe the bug**

**To Reproduce**
1. Start jupyterlab-requirements==0.4.3
2. Install a package

**Expected behavior**
No failure.

**Screenshots**
```
[E 2021-02-23 18:48:45.133 SingleUserLabApp web:1789] Uncaught exception POST /user/fmurdaca@redhat.com/jupyterlab_requirements/pipenv?1614106125047 (::ffff:10.128.4.2)
    HTTPServerRequest(protocol='http', host='jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud', method='POST', uri='/user/fmurdaca@redhat.com/jupyterlab_requirements/pipenv?1614106125047', version='HTTP/1.1', remote_ip='::ffff:10.128.4.2')
    Traceback (most recent call last):
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/app-root/lib64/python3.8/site-packages/jupyterlab_requirements/dependency_management/pipenv.py", line 59, in post
        pipfile_string = Pipfile.from_dict(requirements).to_string()
      File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/pipfile.py", line 416, in from_dict
        thoth_section = ThothPipfileSection.from_dict(dict_.pop("thoth", {}))
      File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/pipfile.py", line 329, in from_dict
        allow_prereleases = dict_.pop("allow_prereleases") or {}
    KeyError: 'allow_prereleases'
```

**Additional context**
Ref: https://github.com/thoth-station/python/blob/4436661793357f543faddbbcc0b9e2bf8f7184a3/thoth/python/pipfile.py#L326
thoth-python version: https://github.com/thoth-station/jupyterlab-requirements/blob/e89cb287108b6a3dec1885ba0cbe87790e0ffef3/Pipfile.lock#L1073

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/python/pull/358/files

**Comment by fridex** [comment]
Sorry for this, silly mistake.

**Comment by pacospace** [comment]
> Sorry for this, silly mistake.

Actually we have this issue in thoth-python 0.15.1 not sure how it is possible
